name: forgot_your_resume
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # arch
  flutter_bloc: 8.1.3
  dartz: 0.10.1
  equatable: 2.0.5
  intl: 0.19.0
  get_it: 7.6.4

  # http  
  dio: 5.4.3+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # tests
  golden_toolkit: 0.15.0
  alchemist: 0.7.0
  mocktail_image_network: 1.0.0
  mocktail: 1.0.3
  bloc_test: 9.1.5
  fake_async: 1.3.1

  flutter_launcher_icons: 0.13.1
  dart_code_metrics: ^5.7.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/resources/
  line_length: 120
  
  fonts:
    enabled: true

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true